name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
      
      - name: Update npm
        run: npm install -g npm@latest
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: false
      
      - name: Verify pnpm
        run: |
          echo "PATH: $PATH"
          which pnpm
          pnpm --version
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Run Lint
        run: pnpm run lint
      
      - name: Run Build
        run: pnpm run build
      
      - name: Build Docs
        run: npx dumi build
      
      - name: Print npm debug log if error
        if: failure()
        run: cat /home/runner/.npm/_logs/*.log
