# .github/workflows/deploy.yml
name: Deploy Dumi Site

on:
  push:
    branches:
      - master # 或 main，根据你的主分支名称修改

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: \${{ runner.os }}-node-\${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            \${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          npm config set registry https://registry.npmmirror.com
          npm cache clean --force
          rm -rf node_modules
          npm install -g dumi
          npm install antd@5.26.0 --save-exact
          npm install --legacy-peer-deps --force
          npm view antd version
          npm ls antd --depth=0
          echo "ANTD VERSION: $(npm list antd | grep antd)"
          cat package.json | grep antd

      - name: Build site
        run: npm run docs:build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs-dist
