# .github/workflows/deploy.yml
name: Deploy Dumi Site

on:
  push:
    branches:
      - master # 或 main，根据你的主分支名称修改

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: \${{ runner.os }}-node-\${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            \${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          npm config set registry https://registry.npmmirror.com
          rm -rf node_modules package-lock.json
          npm install --legacy-peer-deps
          npm install antd@5.26.0 @ant-design/icons@4.7.0 --legacy-peer-deps
          npm install -g dumi@2.4.13

      - name: Build site
        run: |
          npx dumi build
          touch docs-dist/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs-dist
          keep_files: true
