name: Build and Deploy Docs

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - run: pnpm install
      - run: pnpm add -g dumi
      - run: npx dumi build
